# https://github.com/marketplace/actions/translate-markdown-action
name: Translate README

on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding PMC - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
      