# https://github.com/marketplace/actions/translate-markdown-action
name: Translate README

on:
  pull_request:
    branches:
      - main
    paths:
      - './**.md'
      - './Figures/**'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
              # Optional, defaults to author of the commit that triggered the run
              commit_author: Author <actions@github.com>
          
              # Optional, defaults to "actions@github.com"
              commit_user_email: actions@github.com
          
              # Optional, but recommended
              # Defaults to "Apply automatic changes"
              commit_message: Apply automatic changes

              # Optional branch name where commit should be pushed to.
              # Defaults to the current branch.
              branch: $GITHUB_HEAD_REF
              # Optional output file paths, defaults to '[./README.md]'.
              output_file_paths: '[./README.md,./README.fr.md]'
          
              # Categories to automatically sync or transform its contents in the markdown files.
              # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
              categories: '[code-block]'
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: ./
          output_dir: PDF
          images_dir: ./Figures
          # for example <img src="./images/file-name.png">
          image_import: ./Figures
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs


