# https://github.com/marketplace/actions/translate-markdown-action
name: Translate README

on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Commit files
        run:
         |
         sed -i 's/ r Achronim.md//g' README.md
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
         git add *
         git commit -m "removing untranslated text"
         git push
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
     ## copy manualy the file into an other
      - run:
         |
         sed -i $'/<!---vOlv3zg2es--->/{e cat     Achronim.md\n}' README.md
         sed -i $'/<!---vOlv3zg2es--->/{e cat     Achronim.md\n}' README.fr.md
         git add *
         git commit -m "Adding untranslated text"
         git push
        
          

